# Data

I denne øvelsen vil vi se hvordan du kan manipulere datasett med `numpy` og `pandas`. I data science bruker vi ofte store datasett og det er derfor avgjørende å manipulere datasett på en god måte. 

I de følgende oppgavene må du alltid erstatte `___` med kode som gjør hva oppgaven spør om. 

## Grunnlegende om numpy 

Målet med denne oppgaven er å lære de grunnleggende egenskapene til numpy arrayer og hvordan du effektivt bruker dem i arbeidet ditt. 

Vi begynner å laste inn `numpy` pakken som `np`. 

In [40]:
#TODO

# np.describe()
# kombiner spørsmål 5 og 6
# siste på undermatriser

In [41]:
import numpy as np

### Lage numpy array

Det kan være nyttig å vite hvordan du lager en numpy array fra bunnen av for å teste koden din. For eksempel, når du gjør matematikk med store flerdimensjonale arrays, er det fint å sjekke om matematikken fungerer som forventet på små test arrays før du bruker koden på de større arrayene. numpy har mange alternativer for å lage mindre syntetiske matriser.

Lag og skriv ut en numpy array som har to rader og fire kolonner fylt med nuller. Tips: Du kan bruke [numpy.zeros](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html) for å gjøre det på en linje. 

In [42]:
# numpy array med nuller
zeros_array = np.zeros( (2,4) )
print(zeros_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Lag og skriv ut en numpy array som har tre rader og seks kolonner fylt med uniformt fordelte tilfeldige tall mellom 0 og 1. Tips: Du kan bruke [numpy.random.uniform](https://numpy.org/doc/stable/reference/random/generated/numpy.random.uniform.html) for å gjøre det på en linje. 

In [43]:
# numpy array med tilfeldige tall
random_array = np.random.uniform(0,1, (3,6) )
print(random_array)

[[0.38763031 0.95547094 0.19780103 0.57381777 0.75684386 0.2827321 ]
 [0.80843187 0.07901828 0.52951891 0.93304294 0.87546397 0.59556246]
 [0.65411738 0.23392561 0.03035971 0.89963347 0.0985256  0.9229576 ]]


Lag et 1-dimensjonal numpy array som inneholder 8 jevnt fordelte tall fra 0.3 til 1.7. Tips: Du kan bruke enten [`numpy.arange`](https://numpy.org/doc/stable/reference/generated/numpy.arange.html) eller [`numpy.linspace`](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html) for denne oppgaven. 

In [44]:
# numpy array med tall mellom 0.3 og 1.7
range_array = np.linspace( 0.3,1.7, 8)
print(range_array)

[0.3 0.5 0.7 0.9 1.1 1.3 1.5 1.7]


### Dimensjon av numpy array

Numpy arrayer har en rekke egenskaper, som størrelsen og antall dimensjoner. Vi må kunne finne de egenskapene. Noen ganger trenger vi også å endre formen på numpy arrayer. 

Skriv ut formen av `range_array` som du har laget. Tips: Du kan bruke [`shape`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.shape.html) for å lese formen av en numpy array. 

In [45]:
# formen av range_array
array_shape = np.shape(range_array)
print(array_shape)

(8,)


Endre dimensjonen til `range_array` sånn at du får et array med 2 kolonner. Målet er å få en array som har tall [0.3, 0.5, 0.7, 0.9] i første kolonnen og tall [1.1, 1.3, 1.5, 1.7] i andre kolonnen. Tips: Du kan løse oppgaven ved å kun bruke [`numpy.reshape`](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html). Alternativt kan du kombinere [`numpy.reshape`](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html) med [`numpy.transpose`](https://numpy.org/doc/stable/reference/generated/numpy.transpose.html) eller med [`numpy.swapaxes`](https://numpy.org/doc/stable/reference/generated/numpy.swapaxes.html) for denne oppgaven. 

Skriv ut den nye numpy arrayen og dimensjonen av den nye numpy arrayen. 

In [46]:
# endre formen
reshaped_range_array = np.reshape(range_array,(4,2), order="F")
print(reshaped_range_array)
# formen av den nye arrayen
reshaped_array_shape = np.shape(reshaped_range_array)
print(reshaped_array_shape)

[[0.3 1.1]
 [0.5 1.3]
 [0.7 1.5]
 [0.9 1.7]]
(4, 2)


Bruk [`numpy.flatten`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flatten.html) for å lage en 1-dimensjonal numpy array ut av `reshaped_range_array`. Skriv den ut. Er det des samme som `range_array` du begynte med?

In [47]:
# flatten
flattened_range_array = np.reshape(reshaped_range_array,(8))
print(flattened_range_array)

#Den ser helt liktut som ista

[0.3 1.1 0.5 1.3 0.7 1.5 0.9 1.7]


### Kombinere flere array

Når vi har data fra forskjellige kilder er det ofte viktig å kunne kombinere de. Her lærer du hvordan å gjøre det med `numpy`. 

Først lager jeg to matrisser som eksempler. 

In [48]:
# eksempel matriser
mat1 = np.ones(shape=(3, 4))
mat2 = np.arange(2, 14).reshape(3, 4)
print(mat1)
print()
print(mat2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


Det er mange måter å kombinere de matrissene. Her prøver vi det ut på tre forskjellige måter. Kombiner `mat1` med `mat2`, slik at du får
- en ny matrisse med 6 rader og 4 kolonner (Tips: Bruk [`numpy.vstack`](https://numpy.org/doc/stable/reference/generated/numpy.vstack.html)), 
- en ny matrisse med 3 rader og 8 kolonner (Tips: Bruk [`numpy.hstack`](https://numpy.org/doc/stable/reference/generated/numpy.hstack.html)), 
- en ny 3-dimensjonal numpy array med form (2, 3, 4) (Tips: Bruk [`numpy.stack`](https://numpy.org/doc/stable/reference/generated/numpy.stack.html)). 

Det er også et valg hvilken av mat1 og mat2 skal komme først i kombinasjonen. Her tar vi alltid mat1 før mat2. 

In [49]:
# kombinere slik at det blir 6 rader og 4 kolonner
combined_6x4 = np.vstack( (mat1,mat2) )
print(combined_6x4)
print(combined_6x4.shape)

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 2.  3.  4.  5.]
 [ 6.  7.  8.  9.]
 [10. 11. 12. 13.]]
(6, 4)


In [50]:
# kombinere slik at det blir 3 rader og 8 kolonner
combined_3x8 = np.hstack( (mat1,mat2) )
print(combined_3x8)
print(combined_3x8.shape)

[[ 1.  1.  1.  1.  2.  3.  4.  5.]
 [ 1.  1.  1.  1.  6.  7.  8.  9.]
 [ 1.  1.  1.  1. 10. 11. 12. 13.]]
(3, 8)


In [51]:
# kombinere slik at det blir en array med shape (2, 3, 4)
combined_2x3x4 = np.stack( (mat1,mat2) )
print(combined_2x3x4)
print(combined_2x3x4.shape)

[[[ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]]

 [[ 2.  3.  4.  5.]
  [ 6.  7.  8.  9.]
  [10. 11. 12. 13.]]]
(2, 3, 4)


### Undermatriser

Når vi har store numpy arrayer, så vil vi ofte kun se på en liten del om gangen. For å gjøre det må vi kunne ta ut undermatrisser. For å velge ut rader og kolonner bruker vi indeksering. Se [`numpy` dokumentasjonen](https://numpy.org/doc/stable/user/basics.indexing.html#basics-indexing) for en god introduksjon til indeksering. 

Skriv ut følgende undermatriser av `mat2`: 
  - A: De første to kolonnene
  - B: De første to radene og de to første kolonnene. 
  - C: De siste to radene og kolonnene 0 og 2. 
  - D: Radene 1 og 2 og kolonnene 0 og 3

In [52]:
# De første to kolonnene
matA = mat2[0:,:2]
print(matA)

[[ 2  3]
 [ 6  7]
 [10 11]]


In [53]:
# De første to radene og de to første kolonnene. 
matB = mat2[:2,:2]
print(matB)

[[2 3]
 [6 7]]


In [54]:
# De siste to radene og kolonnene 0 og 2. 
matC = mat2[-2:, :][:, [0, 2]]
print(matC)

[[ 6  8]
 [10 12]]


In [55]:
# Radene 1 og 2 og kolonnene 0 og 3 
matD = mat2[1:,:][:, [0, 3]]
print(matD)

[[ 6  9]
 [10 13]]


### Endre data

Når vi har gitt data, så vil vi noen ganger endre på det. For eksempel kan det være at vi har verdier i data som er fysisk umulig, så vi vil sette de til den største mulige verdien.

Endre `mat2` slik at alle tall mindre enn 5 blir satt til 5 og tall større enn 10 blir satt til 10. Tips: Du kan bruke [`numpy.clip`](https://numpy.org/doc/stable/reference/generated/numpy.clip.html).

In [56]:
# mat2 med verdier mellom 5 og 10
clipped_mat2 = np.clip(mat2,5,10)
print(clipped_mat2)

[[ 5  5  5  5]
 [ 6  7  8  9]
 [10 10 10 10]]


I `mat2`, bytt ut alle oddetallene med verdien 1. 

In [57]:
# bytte ut alle oddetallene med verdien 1
odd_mat2 = mat2.copy() # kopier mat2 til en ny numpy array odd_mat2
oddetall = np.where(mat2%2)
odd_mat2[oddetall] = 1
print(odd_mat2)

[[ 2  1  4  1]
 [ 6  1  8  1]
 [10  1 12  1]]


Merk at alle tall i `mat2` er lagret som integer. Gjør de om til `float`. Tips: Bruk [numpy.astype](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.astype.html). 

In [58]:
# gjør om til float
mat2_float = mat2.astype(float)
print(mat2_float)
print(mat2.dtype)
print(mat2_float.dtype)

[[ 2.  3.  4.  5.]
 [ 6.  7.  8.  9.]
 [10. 11. 12. 13.]]
int32
float64


Når vi skriver det ut så ser vi at float skrives med `2.` mens int skrives `2` uten punktum. 

### Matematikk med numpy 

Multipliser alle elementene i `mat2` med `2`. Tips: Ikke bruk løkker, du kan bruke `*` med numpy arrayer. 

In [59]:
# 2 ganger mat2
mat_2x2 = mat2*2
print(mat_2x2)

[[ 4  6  8 10]
 [12 14 16 18]
 [20 22 24 26]]


Regn ut summen av `mat1` og `mat2`. Tips: du kan bruke vanlig `+`. 

In [60]:
# summen
mat_sum = mat1+mat2
print(mat_sum)

[[ 3.  4.  5.  6.]
 [ 7.  8.  9. 10.]
 [11. 12. 13. 14.]]


Regn ut logaritmen av alle elementene i `mat2`. Tips: Bruk [`numpy.log`](https://numpy.org/doc/stable/reference/generated/numpy.log.html).

In [61]:
# logaritmen
log_mat = np.log(mat2)
print(log_mat)

[[0.69314718 1.09861229 1.38629436 1.60943791]
 [1.79175947 1.94591015 2.07944154 2.19722458]
 [2.30258509 2.39789527 2.48490665 2.56494936]]


Regn ut maksimalverdien i `mat2`. Tips: Bruk [`numpy.max`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.max.html).

In [62]:
# maximum
mat_max = np.max(mat2)
print(mat_max)

13


For hver kolonne i `mat2`, regn ut summen. Tips: Bruk [`numpy.sum`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.sum.html) med `axis`-argumentet.

In [63]:
# summe per kolonne
mat_sums = np.sum(mat2,axis=0)
print(mat_sums)

[18 21 24 27]


### Kombiner det du har lært

Så lenge fikk du beskjed på hvert steg hva du skal gjøre og hva slags funksjon som du kan bruke. Nå skal vi prøve å kombinere de forskjellige ting du har lært. 

1. Lag en numpy-array `mat` som består av tre kolonner og 100 rader. Den første kolonnen skal inneholde jevnt fordelte tall fra 0 til 2. Den andre kolonnen skal inneholde uniformt fordelte tilfeldige tall mellom 0 og 5. Den tredje kolonnen skal inneholde et 2-tall hvis den andre kolonnen er større enn 4 og et 0-tall ellers. 
2. Skriv ut de første 10 radene av `mat`. 
3. Finn ut hvor mange av radene har en verdi i andre kolonnen som er større enn 4. 
4. Regn ut maximalverdien av den andre kolonnen. 
5. Regn ut summen av alle den andre kolonnen for alle rad som har den andre kolonnen større enn 4. 
6. Endre alle datapunkter som var større enn 4 til 4. Hvordan har resultatene av spørsmål 4 og 5 forandret seg? 

In [64]:
#1
zero_two = np.linspace ( 0,2, 100)
zero_five = np.random.uniform( 0,5, 100)
depends_col = np.where(zero_five > 4, 2, 0) 

mat = np.column_stack((zero_two, zero_five, depends_col))
#print(mat)

#2
#print(mat[0:10])

#3
mer_enn_fire = np.where(zero_five > 4)
print(np.shape(mer_enn_fire)[1])

#4
max_rad_to = np.max(zero_five)
print(max_rad_to)

#5 Regn ut summen av alle den andre kolonnen for alle rad som har den andre kolonnen større enn 4. 
mer_enn_fire = np.where(zero_five > 4)
sum_larger_four = np.sum(mat[mer_enn_fire])
print(sum_larger_four)

#6 sjekk om denne er riktig også
mat[:, 1] = np.where(mat[:, 1] > 4, 4, mat[:, 1]) 
#print(mat)



17
4.949542283014469
128.8388315197637


In [65]:
# din kode 

## Pandas

Her har vi data om passasjerer på skipet Titanic og informasjon om hvorvidt de overlevde. Noen passasjergrupper hadde bedre sjanser for å overleve. I denne oppgaven skal du bruke passasjerdata for å se om du kan finne noen mønstre. Først importerer vi pandas pakken. 

In [66]:
import pandas as pd

Les inn datasettet titanic.csv i et pandas DataFrame `df`. Tips: Bruk [`pandas.read_csv`](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html). 

In [67]:
# lese inn data
df = pd.read_csv("data/titanic.csv")

Se på de første 10 radene av datasettet. Tips: Bruk [`pandas.DataFrame.head`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.head.html). 

In [68]:
# første 10 radene
første_rad = df.head(10)
print(første_rad)

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54

Beskriv alle kolonnene. For numeriske kolonner, vis i hvert fall gjennomsnitt, minimum, maximum og median. For kategoriske kolonner, vis antall unike verdier og den mest vanlige verdien. Tips: Bruk [`pandas.DataFrame.describe`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html). 

In [69]:
# data beskrivelse
beskrivelse = df.describe(include="all")
beskrivelse

PassengerId    Survived      Pclass                     Name   Sex  \
count    891.000000  891.000000  891.000000                      891   891   
unique          NaN         NaN         NaN                      891     2   
top             NaN         NaN         NaN  Braund, Mr. Owen Harris  male   
freq            NaN         NaN         NaN                        1   577   
mean     446.000000    0.383838    2.308642                      NaN   NaN   
std      257.353842    0.486592    0.836071                      NaN   NaN   
min        1.000000    0.000000    1.000000                      NaN   NaN   
25%      223.500000    0.000000    2.000000                      NaN   NaN   
50%      446.000000    0.000000    3.000000                      NaN   NaN   
75%      668.500000    1.000000    3.000000                      NaN   NaN   
max      891.000000    1.000000    3.000000                      NaN   NaN   

               Age       SibSp       Parch  Ticket        Fare    Cabin  \
count   714.000000  891.000000  891.000000     891  891.000000      204   
unique         NaN         NaN         NaN     681         NaN      147   
top            NaN         NaN         NaN  347082         NaN  B96 B98   
freq           NaN         NaN         NaN       7         NaN        4   
mean     29.699118    0.523008    0.381594     NaN   32.204208      NaN   
std      14.526497    1.102743    0.806057     NaN   49.693429      NaN   
min       0.420000    0.000000    0.000000     NaN    0.000000      NaN   
25%      20.125000    0.000000    0.000000     NaN    7.910400      NaN   
50%      28.000000    0.000000    0.000000     NaN   14.454200      NaN   
75%      38.000000    1.000000    0.000000     NaN   31.000000      NaN   
max      80.000000    8.000000    6.000000     NaN  512.329200      NaN   

       Embarked  
count       889  
unique        3  
top           S  
freq        644  
mean        NaN  
std         NaN  
min         NaN  
25%         NaN  
50%         NaN  
75%         NaN  
max         NaN

Lag en ny `numpy` array med overlevelses-status (kolonnen `Survived`).  Tips: Bruk [`pandas.DataFrame.loc`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html) og [`pandas.DataFrame.to_numpy`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_numpy.html). 

In [70]:
# lage overlevelses-variabel
overlever_df = df.loc[:, 'Survived']
overlever = overlever_df.to_numpy()
print(overlever)

[0 1 1 1 0 0 0 0 1 1 1 1 0 0 0 1 0 1 0 1 0 1 1 1 0 1 0 0 1 0 0 1 1 0 0 0 1
 0 0 1 0 0 0 1 1 0 0 1 0 0 0 0 1 1 0 1 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0
 1 0 0 0 1 1 0 1 1 0 1 1 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0 0 0 0 1 0 0 1 0 0 0 0 1 1 0 0 0 1 0
 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1
 0 1 1 0 0 1 0 1 1 1 1 0 0 1 0 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 1 1 0 1 0 1 0
 0 0 1 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 1 0 0 0 0 0 1 1 1 0 1 1 0 1 1 0 0 0 1 0 0 0 1 0 0 1 0 1 1 1 1 0 0 0 0
 0 0 1 1 1 1 0 1 0 1 1 1 0 1 1 1 0 0 0 1 1 0 1 1 0 0 1 1 0 1 0 1 1 1 1 0 0
 0 1 0 0 1 1 0 1 1 0 0 0 1 1 1 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 0 0 0 1 1 0 0 0 1 1 0 1 0 0 0 1 0 1 1 1 0 1 1 0 0 0 0 1 1 0 0 0 0 0 0
 1 0 0 0 0 1 0 1 0 1 1 0 0 0 0 0 0 0 0 1 1 0 1 1 1 1 0 0 1 0 1 0 0 1 0 0 1
 1 1 1 1 1 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 1 0
 0 0 1 1 0 1 0 0 1 0 0 0 

Regn ut total andel av pasasjerer som overlevde. Tips: Bruk [`numpy.mean`](https://numpy.org/doc/stable/reference/generated/numpy.mean.html) eller [`pandas.DataFrame.mean`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.mean.html). 


In [71]:
# andel som overlevde
andel_overlever = overlever.mean()
print(andel_overlever) 

0.3838383838383838


Regn ut proporsjonen av kvinner og menn som overlevde. Du kan bruke [`pandas.DataFrame.groupby`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html).

In [72]:
# overlevelse blant kvinner og menn
kjonn_overlevelse = df.groupby("Sex")["Survived"].mean().to_frame()
kjonn_overlevelse

Survived
Sex             
female  0.742038
male    0.188908

Regn ut proporsjonen som overlevde i hver klasse (`Pclass`). 

In [73]:
# overlevelse per klasse
klasse_overlevelse = df.groupby("Pclass")["Survived"].mean().to_frame()
klasse_overlevelse

Survived
Pclass          
1       0.629630
2       0.472826
3       0.242363

Lag en ny variabel i `df` med aldersgrupper [0, 18), [18, 60) og [60, 120). Tips: Du kan bruke [`pandas.cut`](https://pandas.pydata.org/docs/reference/api/pandas.cut.html).

In [74]:
# aldersgrupper
bins = [0,18,60,120]
df.loc[:, 'AgeGroup'] = pd.cut(df["Age"],bins, labels = [ "[0, 18)", "[18, 60)", "[60, 120)" ], right=False)
print(df)

     PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ... 

Hvor mange passasjerer er i hver aldersgruppe? Tips: Du kan bruke [`pandas.DataFrame.value_counts`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.value_counts.html). 

In [75]:
# passasjerer per aldersgruppe
passasjerer_per_aldersgruppe = df["AgeGroup"].value_counts()

passasjerer_per_aldersgruppe

[18, 60)     575
[0, 18)      113
[60, 120)     26
Name: AgeGroup, dtype: int64

Regn ut proporsjonen som overlevde i hver aldersgruppe. 

In [76]:
# overlevelse per aldersgruppe
overlevelse_per_aldersgruppe = df.groupby("AgeGroup")["Survived"].mean().to_frame()

Legg til dummy-variabler for hver alderskategori. Tips: Du kan bruke [`pandas.get_dummies`](https://pandas.pydata.org/docs/reference/api/pandas.get_dummies.html). 

In [77]:
# alderskategori dummy variabler
# Create dummies for AgeGroup
age_dummies = pd.get_dummies(df['AgeGroup'], prefix='AgeGroup')
df = pd.concat([df, age_dummies], axis=1)
print(df.head())

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  AgeGroup  \
0      0         A/5 21171   7.2500   NaN        S  [18, 60)   
1      0          PC 17599  71.2833   C85        C  [18, 60)   
2      0  STON/O2. 3101282   7.9250   NaN        S  [18, 60)   
3      0            113803  53.1000  C123        S  [18, 60)   


Regn ut proporsjonen som overlevde i og utenfor aldersgruppen [18, 60) for hver kjønn. 

In [78]:
# andel som overlevde i og utenfor aldersgruppen [18, 60) for hver kjønn. 

# gender within age group [18, 60)
inside_18_60 = df[df['AgeGroup_[18, 60)']].groupby('Sex')['Survived'].mean().to_frame()

# gender outside age group [18, 60)
outside_18_60 = df[~df['AgeGroup_[18, 60)']].groupby('Sex')['Survived'].mean().to_frame()


overlevelse_kjonn_alder = pd.concat( [inside_18_60,outside_18_60])
overlevelse_kjonn_alder

KeyError: "None of [UInt64Index([1, 1, 1, 1, 1, 0, 1, 0, 1, 0,\n             ...\n             1, 1, 1, 1, 1, 1, 1, 0, 1, 1],\n            dtype='uint64', length=891)] are in the [columns]"