# Data

I denne øvelsen vil vi se hvordan du kan manipulere datasett med `numpy` og `pandas`. I data science bruker vi ofte store datasett og det er derfor avgjørende å manipulere datasett på en god måte. 

I de følgende oppgavene må du alltid erstatte `___` med kode som gjør hva oppgaven spør om. 

## Grunnlegende om numpy 

Målet med denne oppgaven er å lære de grunnleggende egenskapene til numpy arrayer og hvordan du effektivt bruker dem i arbeidet ditt. 

Vi begynner å laste inn `numpy` pakken som `np`. 

In [11]:
import numpy as np

### Lage numpy array

Det kan være nyttig å vite hvordan du lager en numpy array fra bunnen av for å teste koden din. For eksempel, når du gjør matematikk med store flerdimensjonale arrays, er det fint å sjekke om matematikken fungerer som forventet på små test arrays før du bruker koden på de større arrayene. numpy har mange alternativer for å lage mindre syntetiske matriser.

Lag og skriv ut en numpy array som har to rader og fire kolonner fylt med nuller. Tips: Du kan bruke [numpy.zeros](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html) for å gjøre det på en linje. 

In [7]:
# numpy array med nuller
zeros_array = np.zeros( (4,2) )
print(zeros_array)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


Lag og skriv ut en numpy array som har tre rader og seks kolonner fylt med uniformt fordelte tilfeldige tall mellom 0 og 1. Tips: Du kan bruke [numpy.random.uniform](https://numpy.org/doc/stable/reference/random/generated/numpy.random.uniform.html) for å gjøre det på en linje. 

In [13]:
# numpy array med tilfeldige tall
random_array = np.random.uniform(0,1, (6,3) )
print(random_array)

[[0.46957178 0.76625992 0.94640906]
 [0.8833962  0.83379887 0.5525824 ]
 [0.46091988 0.38573    0.49582712]
 [0.0273408  0.00262067 0.2978878 ]
 [0.79825446 0.69098736 0.84335866]
 [0.15930774 0.21997818 0.60122651]]


Lag et 1-dimensjonal numpy array som inneholder 8 jevnt fordelte tall fra 0.3 til 1.7. Tips: Du kan bruke enten [`numpy.arange`](https://numpy.org/doc/stable/reference/generated/numpy.arange.html) eller [`numpy.linspace`](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html) for denne oppgaven. 

In [21]:
# numpy array med tall mellom 0.3 og 1.7
range_array = np.linspace( 0.3,1.7, 8)
print(range_array)

[0.3 0.5 0.7 0.9 1.1 1.3 1.5 1.7]


### Dimensjon av numpy array

Numpy arrayer har en rekke egenskaper, som størrelsen og antall dimensjoner. Vi må kunne finne de egenskapene. Noen ganger trenger vi også å endre formen på numpy arrayer. 

Skriv ut formen av `range_array` som du har laget. Tips: Du kan bruke [`shape`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.shape.html) for å lese formen av en numpy array. 

In [22]:
# formen av range_array
array_shape = np.shape(range_array)
print(array_shape)

(8,)


Endre dimensjonen til `range_array` sånn at du får et array med 2 kolonner. Målet er å få en array som har tall [0.3, 0.5, 0.7, 0.9] i første kolonnen og tall [1.1, 1.3, 1.5, 1.7] i andre kolonnen. Tips: Du kan løse oppgaven ved å kun bruke [`numpy.reshape`](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html). Alternativt kan du kombinere [`numpy.reshape`](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html) med [`numpy.transpose`](https://numpy.org/doc/stable/reference/generated/numpy.transpose.html) eller med [`numpy.swapaxes`](https://numpy.org/doc/stable/reference/generated/numpy.swapaxes.html) for denne oppgaven. 

Skriv ut den nye numpy arrayen og dimensjonen av den nye numpy arrayen. 

In [43]:
# endre formen
reshaped_range_array = np.reshape(range_array,(2,4))
print(reshaped_range_array)
# formen av den nye arrayen
reshaped_array_shape = np.shape(reshaped_range_array)
print(reshaped_array_shape)

[[0.3 0.5 0.7 0.9]
 [1.1 1.3 1.5 1.7]]
(2, 4)


Bruk [`numpy.flatten`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flatten.html) for å lage en 1-dimensjonal numpy array ut av `reshaped_range_array`. Skriv den ut. Er det des samme som `range_array` du begynte med?

In [29]:
# flatten
flattened_range_array = np.reshape(reshaped_range_array,(8))
print(flattened_range_array)

[0.3 0.5 0.7 0.9 1.1 1.3 1.5 1.7]


### Kombinere flere array

Når vi har data fra forskjellige kilder er det ofte viktig å kunne kombinere de. Her lærer du hvordan å gjøre det med `numpy`. 

Først lager jeg to matrisser som eksempler. 

In [30]:
# eksempel matriser
mat1 = np.ones(shape=(3, 4))
mat2 = np.arange(2, 14).reshape(3, 4)
print(mat1)
print()
print(mat2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


Det er mange måter å kombinere de matrissene. Her prøver vi det ut på tre forskjellige måter. Kombiner `mat1` med `mat2`, slik at du får
- en ny matrisse med 6 rader og 4 kolonner (Tips: Bruk [`numpy.vstack`](https://numpy.org/doc/stable/reference/generated/numpy.vstack.html)), 
- en ny matrisse med 3 rader og 8 kolonner (Tips: Bruk [`numpy.hstack`](https://numpy.org/doc/stable/reference/generated/numpy.hstack.html)), 
- en ny 3-dimensjonal numpy array med form (2, 3, 4) (Tips: Bruk [`numpy.stack`](https://numpy.org/doc/stable/reference/generated/numpy.stack.html)). 

Det er også et valg hvilken av mat1 og mat2 skal komme først i kombinasjonen. Her tar vi alltid mat1 før mat2. 

In [32]:
# kombinere slik at det blir 6 rader og 4 kolonner
combined_6x4 = np.vstack( (mat1,mat2) )
print(combined_6x4)
print(combined_6x4.shape)

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 2.  3.  4.  5.]
 [ 6.  7.  8.  9.]
 [10. 11. 12. 13.]]
(6, 4)


In [33]:
# kombinere slik at det blir 3 rader og 8 kolonner
combined_3x8 = np.hstack( (mat1,mat2) )
print(combined_3x8)
print(combined_3x8.shape)

[[ 1.  1.  1.  1.  2.  3.  4.  5.]
 [ 1.  1.  1.  1.  6.  7.  8.  9.]
 [ 1.  1.  1.  1. 10. 11. 12. 13.]]
(3, 8)


In [34]:
# kombinere slik at det blir en array med shape (2, 3, 4)
combined_2x3x4 = np.stack( (mat1,mat2) )
print(combined_2x3x4)
print(combined_2x3x4.shape)

[[[ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]]

 [[ 2.  3.  4.  5.]
  [ 6.  7.  8.  9.]
  [10. 11. 12. 13.]]]
(2, 3, 4)


### Undermatriser

Når vi har store numpy arrayer, så vil vi ofte kun se på en liten del om gangen. For å gjøre det må vi kunne ta ut undermatrisser. For å velge ut rader og kolonner bruker vi indeksering. Se [`numpy` dokumentasjonen](https://numpy.org/doc/stable/user/basics.indexing.html#basics-indexing) for en god introduksjon til indeksering. 

Skriv ut følgende undermatriser av `mat2`: 
  - A: De første to kolonnene
  - B: De første to radene og de to første kolonnene. 
  - C: De siste to radene og kolonnene 0 og 2. 
  - D: Radene 1 og 2 og kolonnene 0 og 3

In [57]:
# De første to kolonnene
matA = mat2[0:,:2]
print(matA)

[[ 2  3]
 [ 6  7]
 [10 11]]


In [68]:
# De første to radene og de to første kolonnene. 
matB = mat2[:2,:2]
print(matB)

[[2 3]
 [6 7]]


In [107]:
# De siste to radene og kolonnene 0 og 2. 
matC = mat2[-2:, :][:, [0, 2]]
print(matC)

[[ 6  8]
 [10 12]]


In [108]:
# Radene 1 og 2 og kolonnene 0 og 3
matD = mat2[1:,:][:, [0, 3]]
print(matD)

[[ 6  9]
 [10 13]]


### Endre data

Når vi har gitt data, så vil vi noen ganger endre på det. For eksempel kan det være at vi har verdier i data som er fysisk umulig, så vi vil sette de til den største mulige verdien.

Endre `mat2` slik at alle tall mindre enn 5 blir satt til 5 og tall større enn 10 blir satt til 10. Tips: Du kan bruke [`numpy.clip`](https://numpy.org/doc/stable/reference/generated/numpy.clip.html).

In [109]:
# mat2 med verdier mellom 5 og 10
clipped_mat2 = np.clip(mat2,5,10)
print(clipped_mat2)

[[ 5  5  5  5]
 [ 6  7  8  9]
 [10 10 10 10]]


I `mat2`, bytt ut alle oddetallene med verdien 1. 

In [114]:
# bytte ut alle oddetallene med verdien 1
odd_mat2 = mat2.copy() # kopier mat2 til en ny numpy array odd_mat2
oddetall = np.where(mat2%2)
odd_mat2[oddetall] = 1
print(odd_mat2)

[[ 2  1  4  1]
 [ 6  1  8  1]
 [10  1 12  1]]


Merk at alle tall i `mat2` er lagret som integer. Gjør de om til `float`. Tips: Bruk [numpy.astype](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.astype.html). 

In [112]:
# gjør om til float
mat2_float = mat2.astype(float)
print(mat2_float)
print(mat2.dtype)
print(mat2_float.dtype)

[[ 2.  3.  4.  5.]
 [ 6.  7.  8.  9.]
 [10. 11. 12. 13.]]
int64
float64


Når vi skriver det ut så ser vi at float skrives med `2.` mens int skrives `2` uten punktum. 

### Matematikk med numpy 

Multipliser alle elementene i `mat2` med `2`. Tips: Ikke bruk løkker, du kan bruke `*` med numpy arrayer. 

In [115]:
# 2 ganger mat2
mat_2x2 = mat2*2
print(mat_2x2)

[[ 4  6  8 10]
 [12 14 16 18]
 [20 22 24 26]]


Regn ut summen av `mat1` og `mat2`. Tips: du kan bruke vanlig `+`. 

In [116]:
# summen
mat_sum = mat1+mat2
print(mat_sum)

[[ 3.  4.  5.  6.]
 [ 7.  8.  9. 10.]
 [11. 12. 13. 14.]]


Regn ut logaritmen av alle elementene i `mat2`. Tips: Bruk [`numpy.log`](https://numpy.org/doc/stable/reference/generated/numpy.log.html).

In [118]:
# logaritmen
log_mat = np.log(mat2)
print(log_mat)

[[0.69314718 1.09861229 1.38629436 1.60943791]
 [1.79175947 1.94591015 2.07944154 2.19722458]
 [2.30258509 2.39789527 2.48490665 2.56494936]]


Regn ut maksimalverdien i `mat2`. Tips: Bruk [`numpy.max`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.max.html).

In [120]:
# maximum
mat_max = np.max(mat2)
print(mat_max)

13


For hver kolonne i `mat2`, regn ut summen. Tips: Bruk [`numpy.sum`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.sum.html) med `axis`-argumentet.

In [127]:
# summe per kolonne
mat_sums = np.sum(mat2,axis=0)
print(mat_sums)

[18 21 24 27]


### Kombiner det du har lært

Så lenge fikk du beskjed på hvert steg hva du skal gjøre og hva slags funksjon som du kan bruke. Nå skal vi prøve å kombinere de forskjellige ting du har lært. 

1. Lag en numpy-array `mat` som består av tre kolonner og 100 rader. Den første kolonnen skal inneholde jevnt fordelte tall fra 0 til 2. Den andre kolonnen skal inneholde uniformt fordelte tilfeldige tall mellom 0 og 5. Den tredje kolonnen skal inneholde et 2-tall hvis den andre kolonnen er større enn 4 og et 0-tall ellers. 
2. Skriv ut de første 10 radene av `mat`. 
3. Finn ut hvor mange av radene har en verdi i andre kolonnen som er større enn 4. 
4. Regn ut maximalverdien av den andre kolonnen. 
5. Regn ut summen av alle den andre kolonnen for alle rad som har den andre kolonnen større enn 4. 
6. Endre alle datapunkter som var større enn 4 til 4. Hvordan har resultatene av spørsmål 4 og 5 forandret seg? 

In [5]:
#1
zero_two = np.linspace ( 0,2, 100)
zero_five = np.random.uniform( 0,5, 100)
depends_col = np.where(zero_five > 4, 2, 0) 

mat = np.column_stack((zero_two, zero_five, depends_col))
#print(mat)

#2
#print(mat[0:10])

#3
mer_enn_fire = np.where(zero_five > 4)
print(np.shape(mer_enn_fire)[1])

#4
max_rad_to = np.max(zero_five)
print(max_rad_to)

#5
mer_enn_fire = np.where(zero_five > 4)
sum_larger_four = np.sum(mat[mer_enn_fire])
print(sum_larger_four)

#6
mat[:, 1] = np.where(mat[:, 1] > 4, 4, mat[:, 1]) 
print(mat)



21
4.952742899116761
163.74660200835345
[[0.         4.         2.        ]
 [0.02020202 4.         2.        ]
 [0.04040404 1.70880357 0.        ]
 [0.06060606 3.35640145 0.        ]
 [0.08080808 2.58687548 0.        ]
 [0.1010101  1.50798665 0.        ]
 [0.12121212 3.21617004 0.        ]
 [0.14141414 2.82344452 0.        ]
 [0.16161616 2.79431713 0.        ]
 [0.18181818 3.40089573 0.        ]
 [0.2020202  1.68969525 0.        ]
 [0.22222222 0.02825017 0.        ]
 [0.24242424 4.         2.        ]
 [0.26262626 2.86352863 0.        ]
 [0.28282828 0.66254068 0.        ]
 [0.3030303  2.57646901 0.        ]
 [0.32323232 0.42387763 0.        ]
 [0.34343434 1.85635314 0.        ]
 [0.36363636 4.         2.        ]
 [0.38383838 2.14972201 0.        ]
 [0.4040404  1.44248416 0.        ]
 [0.42424242 1.31466164 0.        ]
 [0.44444444 2.47675501 0.        ]
 [0.46464646 1.67714888 0.        ]
 [0.48484848 0.06693501 0.        ]
 [0.50505051 3.48415983 0.        ]
 [0.52525253 0.98351431 

In [191]:
# din kode 

## Pandas

Her har vi data om passasjerer på skipet Titanic og informasjon om hvorvidt de overlevde. Noen passasjergrupper hadde bedre sjanser for å overleve. I denne oppgaven skal du bruke passasjerdata for å se om du kan finne noen mønstre. Først importerer vi pandas pakken. 

In [3]:
import pandas as pd

Les inn datasettet titanic.csv i et pandas DataFrame `df`. Tips: Bruk [`pandas.read_csv`](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html). 

In [4]:
# lese inn data
df = pd.read_csv("titanic.csv")

Se på de første 10 radene av datasettet. Tips: Bruk [`pandas.DataFrame.head`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.head.html). 

In [6]:
# første 10 radene
første_rad = df.head(10)
print(første_rad)

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54

Beskriv alle kolonnene. For numeriske kolonner, vis i hvert fall gjennomsnitt, minimum, maximum og median. For kategoriske kolonner, vis antall unike verdier og den mest vanlige verdien. Tips: Bruk [`pandas.DataFrame.describe`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html). 

In [9]:
# data beskrivelse
beskrivelse = df.describe()

Lag en ny `numpy` array med overlevelses-status (kolonnen `Survived`).  Tips: Bruk [`pandas.DataFrame.loc`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html) og [`pandas.DataFrame.to_numpy`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_numpy.html). 

In [19]:
# lage overlevelses-variabel
overlever_df = df.loc[:, 'Survived']
overlever = overlever_df.to_numpy()
print(overlever)

[0 1 1 1 0 0 0 0 1 1 1 1 0 0 0 1 0 1 0 1 0 1 1 1 0 1 0 0 1 0 0 1 1 0 0 0 1
 0 0 1 0 0 0 1 1 0 0 1 0 0 0 0 1 1 0 1 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0
 1 0 0 0 1 1 0 1 1 0 1 1 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0 0 0 0 1 0 0 1 0 0 0 0 1 1 0 0 0 1 0
 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1
 0 1 1 0 0 1 0 1 1 1 1 0 0 1 0 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 1 1 0 1 0 1 0
 0 0 1 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 1 0 0 0 0 0 1 1 1 0 1 1 0 1 1 0 0 0 1 0 0 0 1 0 0 1 0 1 1 1 1 0 0 0 0
 0 0 1 1 1 1 0 1 0 1 1 1 0 1 1 1 0 0 0 1 1 0 1 1 0 0 1 1 0 1 0 1 1 1 1 0 0
 0 1 0 0 1 1 0 1 1 0 0 0 1 1 1 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 0 0 0 1 1 0 0 0 1 1 0 1 0 0 0 1 0 1 1 1 0 1 1 0 0 0 0 1 1 0 0 0 0 0 0
 1 0 0 0 0 1 0 1 0 1 1 0 0 0 0 0 0 0 0 1 1 0 1 1 1 1 0 0 1 0 1 0 0 1 0 0 1
 1 1 1 1 1 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 1 0
 0 0 1 1 0 1 0 0 1 0 0 0 

Regn ut total andel av pasasjerer som overlevde. Tips: Bruk [`numpy.mean`](https://numpy.org/doc/stable/reference/generated/numpy.mean.html) eller [`pandas.DataFrame.mean`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.mean.html). 


In [18]:
# andel som overlevde
andel_overlever = overlever.mean()
print(andel_overlever) 

0.3838383838383838


Regn ut proporsjonen av kvinner og menn som overlevde. Du kan bruke [`pandas.DataFrame.groupby`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html).

In [28]:
# overlevelse blant kvinner og menn
kjonn_overlevelse = df.groupby("Sex")["Survived"].mean()
kjonn_overlevelse

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

Regn ut proporsjonen som overlevde i hver klasse (`Pclass`). 

In [29]:
# overlevelse per klasse
klasse_overlevelse = df.groupby("Pclass")["Survived"].mean()
klasse_overlevelse

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

Lag en ny variabel i `df` med aldersgrupper [0, 18), [18, 60) og [60, 120). Tips: Du kan bruke [`pandas.cut`](https://pandas.pydata.org/docs/reference/api/pandas.cut.html).

In [30]:
# aldersgrupper
df.loc[:, 'AgeGroup'] = pd.cut(df["Age"],[0,20])

ValueError: Input array must be 1 dimensional

Hvor mange passasjerer er i hver aldersgruppe? Tips: Du kan bruke [`pandas.DataFrame.value_counts`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.value_counts.html). 

In [ ]:
# passasjerer per aldersgruppe
passasjerer_per_aldersgruppe = ___
passasjerer_per_aldersgruppe

Regn ut proporsjonen som overlevde i hver aldersgruppe. 

In [ ]:
# overlevelse per aldersgruppe
overlevelse_per_aldersgruppe = ___
overlevelse_per_aldersgruppe

Legg til dummy-variabler for hver alderskategori. Tips: Du kan bruke [`pandas.get_dummies`](https://pandas.pydata.org/docs/reference/api/pandas.get_dummies.html). 

In [ ]:
# alderskategori dummy variabler
df = ___

Regn ut proporsjonen som overlevde i og utenfor aldersgruppen [18, 60) for hver kjønn. 

In [ ]:
# andel som overlevde i og utenfor aldersgruppen [18, 60) for hver kjønn. 
overlevelse_kjonn_alder = ___
overlevelse_kjonn_alder